apiVersion: v2
name: pagopa-reporting-orgs-enrollment
description: Microservice that handles the GPD reporting organizations enrollment
type: application
version: 0.13.0
appVersion: 0.1.8
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
